name: go-server # you probably want to 'snapcraft register <name>'
base: core24 # the base snap is the execution environment for this snap
version: '0.2' # just for humans, typically '1.2+git' or '1.3.2'
summary: A simple Go HTTP server
description: |
  A basic Go HTTP server with hello-world and health check endpoints.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  go-server:
    command: bin/go-server
    plugs: [network-bind]

parts:
  go-server:
    # See 'snapcraft plugins'
    plugin: go
    build-snaps: [go/latest/stable]
    source: https://github.com/shreyas1307/go-server
    source-type: git
